name: Create admin user
description: Creates an admin user from templates

inputs:
  okapi-host:
    description: The okapi host url
    required: true
  okapi-token:
    description: The okapi supertenant token
    required: true
  tenant-id:
    description: The id of the tenant to create an admin on
    required: true
  admin-password:
    description: The password of the account to be created
    required: true
  user-template:
    description: User template file
    required: false
    default: ./templates/admin_user.json.j2
  perms-template:
    description: User permissions template file
    required: false
    default: ./templates/admin_perms.json.j2
  creds-template:
    description: User credentials template file
    required: false
    default: ./templates/admin_creds.json.j2
  authtoken-version:
    description: version of mod-authtoken
    required: false
    default: mod-authtoken-2.15.2

runs:
  using: "composite"
  steps: 
    - name: Ensure dependencies are installed
      shell: bash
      run: |
        if ! command -v http &> /dev/null; then
          echo "Installing httpie..."
          pip install httpie
        else
          echo "httpie already installed"
        fi

        if ! command -v jq &> /dev/null; then
          echo "Installing jq..."
          sudo apt-get update && sudo apt-get install -y jq
        else
          echo "jq already installed"
        fi

    - name: Disable mod-authtoken
      id: disable_authtoken
      shell: bash
      run: |
        OKAPI_URL="${{ inputs.okapi-host }}"
        OKAPI_TOKEN="${{ inputs.okapi-token }}"
        TENANT="${{ inputs.tenant-id }}"
        MODULE_ID="${{ inputs.authtoken-version }}"
        PAYLOAD=$(jq -n \
          --arg id "$MODULE_ID" \
          --arg action "disable" \
          '[{id: $id, action: $action}]')

        echo $PAYLOAD
    
        echo "Disabling mod-authtoken for tenant '$TENANT'..."
    
        set +e
        RESPONSE=$(echo "$PAYLOAD" | \
          http --check-status POST "$OKAPI_URL/_/proxy/tenants/$TENANT/install?depCheck=false" \
          "x-okapi-tenant:supertenant" \
          "x-okapi-token:$OKAPI_TOKEN")
        STATUS=$?
        set -e
    
        echo "Response:"
        echo "$RESPONSE"
    
        if [[ $STATUS -ne 0 ]]; then
          echo "Request failed with status $STATUS"
          exit $STATUS
        fi

    - name: run admin creation script
      shell: bash
      env:
        OKAPI_HOST: ${{ inputs.okapi-host }}
        OKAPI_TOKEN: ${{ inputs.okapi-token }}
        TENANT_ID: ${{ inputs.tenant-id }}
        ADMIN_PASSWORD: ${{ inputs.admin-password }}
      run: |
        python3 "${{ github.action_path }}/scripts/admin_perms.py"

    - name: Enable mod-authtoken
      shell: bash
      run: |
        MODULE_ID="${{ inputs.authtoken-version }}"
        OKAPI_URL="${{ inputs.okapi-host }}"
        OKAPI_TOKEN="${{ inputs.okapi-token }}"
        TENANT="${{ inputs.tenant-id }}"
        PAYLOAD=$(jq -n \
          --arg id "$MODULE_ID" \
          --arg action "enable" \
          '[{id: $id, action: $action}]')

        echo $PAYLOAD
        
        echo "$PAYLOAD" | \
          http --check-status POST "$OKAPI_URL/_/proxy/tenants/$TENANT/install?depCheck=false" \
          "x-okapi-tenant:supertenant" \
          "x-okapi-token:$OKAPI_TOKEN"
