name: Build a webpack with yarn
description: Builds a webpack

inputs:
  okapi:
    description: The okapi host url
    required: true
  tenant:
    description: The okapi supertenant token
    required: true
  reshare-transpile:
    description: use special reshare transpile invocation
    required: false
    type: boolean
    default: false
  node-version:
    description: version of node to set up
    required: false
    default: 18

runs:
  using: "composite"
  steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }} 

      - name: Install Yarn
        run: npm install -g yarn

      - name: Add FOLIO registry to yarn
        run: yarn config set @folio:registry https://repository.folio.org/repository/npm-folio/

      - name: Do yarn install
        run: yarn install

      - name: Upload yarn.lock
        uses: actions/upload-artifact@v4
        with:
          name: yarn.lock
          path: ./yarn.lock

      - name: run build scripts
        run: |

      - name: Run stripes build
        if: ${{ github.event.inputs.reshare-transpile == 'false' }}
        run: |
          yarn build output --okapi ${{ inputs.okapi }} --tenant ${{ inputs.tenant }} && mv output ${{ inputs.tenant }}

      - name: Run stripes build with reshare transpile tokens set
        if: ${{ github.event.inputs.reshare-transpile == 'true' }}
        run: |
          STRIPES_TRANSPILE_TOKENS=@k-int yarn build output --okapi ${{ inputs.okapi }} --tenant ${{ inputs.tenant }} && mv output ${{ inputs.tenant }}
